name: Update-Posts

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python posts.py
      - name: Git Commit
        run: |
          git config --local user.email "blancpanda@users.noreply.github.com"
          git config --local user.name "blancpanda"
          git add README.md
          git diff --cached --quiet || (git commit -m "Update posts" && git push origin main)
